### ISSUE TITLE
Some text is hidden in About page due

### ISSUE THREAD

**Issue by RenCos** [daniil-lebedev/cool-site-of-friends#11]
The text on the About page is covered by the headings when the window isn't set to fullscreen
![evidence for issue](https://user-images.githubusercontent.com/44414868/119581968-96b65d80-bdbb-11eb-8494-fc964e3f0159.PNG)

**Comment by RenCos** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Some text is hidden in About page due](https://trello.com/c/enlGLqvV/40-some-text-is-hidden-in-about-page-due)

**Comment by daniil-lebedev** [comment]
let's start working on it tomorrow.

**Comment by daniil-lebedev** [comment]
What screen resolution was it?
And the browser?

**Comment by RenCos** [comment]
> 
> 
> What screen resolution was it?
> 
> And the browser?

Not too sure I had just manual shortened the chrome window.

**Comment by daniil-lebedev** [comment]
Yeah I managed to get it. Not sure how to fix it. But I got an idea how.

**Comment by RenCos** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User accounts](https://trello.com/c/99Hfy9sE/20-user-accounts)

**Comment by RenCos** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User accounts](https://trello.com/c/99Hfy9sE/20-user-accounts)

**Comment by DavidAni44** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Incorrect formatting bug](https://trello.com/c/NIMswHLh/60-incorrect-formatting-bug)
